package com.nrojt.countdownwidget.data

import android.content.Context
import androidx.datastore.core.CorruptionException
import androidx.datastore.core.DataStore
import androidx.datastore.core.Serializer
import androidx.datastore.dataStore
import androidx.datastore.preferences.protobuf.InvalidProtocolBufferException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.InputStream
import java.io.OutputStream
import com.nrojt.countdownwidget.CountdownWidgetParams // this class is generated by protobuf from the proto file. Will give errors before first build, cause it's not generated yet.

object CountdownWidgetParamSerializer : Serializer<CountdownWidgetParams> {
    override val defaultValue: CountdownWidgetParams = CountdownWidgetParams.getDefaultInstance()

    override suspend fun readFrom(input: InputStream): CountdownWidgetParams = withContext(Dispatchers.IO) {
        try {
            return@withContext CountdownWidgetParams.parseFrom(input)
        } catch (e : InvalidProtocolBufferException) {
            throw CorruptionException("Cannot read proto.", e)
        }
    }

    override suspend fun writeTo(t: CountdownWidgetParams, output: OutputStream) = withContext(Dispatchers.IO) {
        t.writeTo(output)
    }
}

val Context.countdownWidgetParamDataStore : DataStore<CountdownWidgetParams> by dataStore(
    fileName = "countdown_widget_params.pb",
    serializer = CountdownWidgetParamSerializer
)